name: Build and publish desktop app
on:
  workflow_dispatch:

concurrency:
  group: 'publish'
  cancel-in-progress: true

jobs:
  build:
    strategy:
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
#    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GCLIENT }}
   publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Aggiungi qui i passaggi per pubblicare i tuoi file

    # Aggiungi questa sezione per indicare "publish = always"
    if: always()

